### Create a new locale for a given application
POST https://127.0.0.1:8000/api/translations/locales/add
Accept: application/json
Content-Type: application/json
Authorization: {{app_uuid}}

{
  "locale": "uk"
}

### Set locale as active for a given application
GET https://127.0.0.1:8000/api/translations/locales/set-active
Accept: application/json
Authorization: {{app_uuid}}
Accept-Language: {{accept_language}}

### Set locale as inactive for a given application
GET https://127.0.0.1:8000/api/translations/locales/set-inactive
Accept: application/json
Authorization: {{app_uuid}}
Accept-Language: {{accept_language}}
