### Get all translations for all languages for a given application
GET https://127.0.0.1:8000/api/translations/all
Accept: application/json
Content-Type: application/json
Authorization: {{app_uuid}}

###