### Get all translations for all languages for a given application
GET https://127.0.0.1:8000/api/translations/all
Accept: application/json
Content-Type: application/json
Authorization: 2b7a3ff2-b754-4a39-a8d9-564372677ffd

###