framework:
    cache:
        prefix_seed: nations-original/translations-ms
        app: cache.adapter.redis
        system: cache.adapter.redis
        default_redis_provider: '%env(REDIS_CACHE_URL)%'
        pools:
            doctrine.result_cache_pool:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_CACHE_URL)%'
            doctrine.system_cache_pool:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_CACHE_URL)%'
            doctrine.query_cache_pool:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_CACHE_URL)%'
